### ISSUE TITLE
count doesn't update on clicking in home.vue

### ISSUE THREAD

**Issue by tsalufe** [meteor-vue/guide#1]
On my local (MacPro + Chrome), clicking on the button doesn't update the count number. However, after clicking on "Go to Blaze page" then "Go to Home page", I can see number changed to the correct one. 
Also, as a work around, I assigned the counter outside home.vue component scope to this.counter(added in component data() too) at component created and use this.counter.get/set inside home.vue component in place of counter.get/set. Then the number updates.
Maybe vuejs doesn't accept external ReactiveVar?

**Comment by mitar** [comment]
This happens if you do not clone recursively and do not get the `packages/tracker` git submodule. I will update README to make sure this is clear.
